###创建账号
POST http://localhost:8080/account/
Content-Type: application/json

{
  "number": "1212",
  "customerId": "3231",
  "amount": 1
}

###查看所有账号信息
GET http://localhost:8080/account/

###根据id查找账号
GET http://localhost:8080/account/0187007e-f7a9-488a-a305-19570d089cc7

###根据customerId查找
GET http://localhost:8080/account/customer/3231

###根据id查找账号(先从缓存获取)
GET http://localhost:8080/account/cache/0187007e-f7a9-488a-a305-19570d089cc7

###根据id删除账号
DELETE http://localhost:8080/account/0187007e-f7a9-488a-a305-19570d089cc7
